project_id = "pxyyncsnjpuwvnwyfdwx"

[functions.auth-api]
verify_jwt = false

[functions.links-api]
verify_jwt = false

[functions.paystack-api]
verify_jwt = false

[functions.store-api]
verify_jwt = false

[functions.storefront-api]
verify_jwt = false

[functions.transaction-api]
verify_jwt = false

[functions.wallet-api]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.admin-setup]
verify_jwt = false

[functions.otp-sms]
verify_jwt = false

[functions.ai-generate-product]
verify_jwt = false

[functions.escrow-api]
verify_jwt = false

[functions.disputes-api]
verify_jwt = false

[functions.mpesa-api]
verify_jwt = false

[functions.intasend-api]
verify_jwt = false

[functions.validate-payment]
verify_jwt = false

[functions.sms-notifications]
verify_jwt = false

[functions.review-requests-job]
verify_jwt = false

[functions.pesapal-api]
verify_jwt = false
